from ubuntu 
run apt-get update -y
run apt-get install net-tools -y
run apt-get install python3 -y
run apt install iputils-ping -y
copy potato.py . 
copy house house.txt 
run  apt-get install curl -y
copy index.html .
copy index2.html .
run apt-get install vim -y

expose 80
#docker build -t jesseserver . 
 #docker run -i -t jesseserver /bin/bash
 
